import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Header from "../components/Header";
import Main from "../components/Main";

export default function Home() {
    return (
        <>
            <Head>
                <title>#budget10</title>
                <meta name="description" content="Generated by create next app"/>
                <!--link rel="icon" href="/favicon.ico"/-->
                <link rel="shortcut icon" type="image/x-icon" href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAF6ElEQVRYhc2XXWgTWRTHJwg+qQg++WRFFhGxVaxiakxbuqn5mtrasuAHVkElqHSxIuwq1Fa36rprC9rAPtiAGrFmi9oSQ6FV25ra1EziOFptHwxGhdZiqTY0H52589+HdCZJ81EVhb1wYMi995zf/Z9zJ2co6v8wPvXQy4nXcExwa/RTvVuX/qg4U71blwpujZ54Dcc+9dDL5QniKm4UHIUQXTqAMfgJS58P9WuzvlfgUL82i7D0eTAGv+jSQXAUgriKGymKoiiAUog9BfZAUzYCZiX4djXA0ICXniBu7alxx65F3xp43LFrEXFrT8FLT4ChwberETArEWjKhthTYAcoBWWz2eaht6AzYFZCsilL3owaNMAYhnkXrQIoxZcGBigF76JVYAzDYGiILh2mLHmIj4Hegk6bzTaPoiiKIg/yb0gKSITB5pwYhJeeEAa0lQClACjF+649S+BS/4SBglwMFOTCpf7pfdeeJdK8MKCtlE4tunQINudgtn/yIP+GTEy82+oilix5Ad+uBt+uhtihmlGBBhhjCG5dMzyGR2AMfniiAcDQiD4b/PAYHsGtawZjDElzYodK9if5j1iyQLzb6mQA4Yl2e7hFFaW8vAKRu0WQ6GMAyRa5W4RwiyrjGsmH4ChE4PIKBJqyEW5RQXii3R7LWZ9+Ge7nj0gyha3K1A6dxRAchWkBBEch4CxOuTdsjcmP+/kj6NMvkwEGbbXz4dK4JYmE25vTniZgVsqnigeYPTfbhNubYwXo0rgHbbXzEyqXsHRd2KpEZA5Jw9bYVY0H4NvV6ZWTFGtRIWxVgrB0HTV7wKvJhbM4NFfeBUehHCgeIGxVJqQnbT04i0PwanKTACbu7F0MLz2SyQEYGmJ3ESKWrCSAiCULYndRxr0zV3pk4s7exckKuIs08dcnLYCzGJHr2ckA17MhpinARDOG4C7SJAOwxnNzb/76a5jSWOO5ZACPvjNj8T0qAd+fMqcJv/H90bUZATz6zoTg77v2LMHT6Ht7tvH9NOr352PtRiXK9JswYk8v84i9GGX6TVi7UYn6/flJwLI9NQy/79qzJPFFlKYARzu3YvW6DViVsx6rctbjxhlNWoAbZzTyutXrNmC0c2vaQkx4EeGxek26Agx0l2DLphiAvcGYFsDeYJTXbdm0AYHudKkwhvBYvSYGMFCQmyln3DU96o8W4eYlXXpZZ9J185IO9UeLwF3TZ66DgYLcLwb4MfazSgaYZJvKhJcnIPobBdFvJuKbKzPPjcI0Ww3x+T6S6rThRyUpbwcYGuLzfWSarZb9RH2aiehvFISXJzDJNpXJAJ9f3a3hh+uD02w1RM4EkTOBcIfBD50lot9MeJ8VImeSnU87yjF+4DA+7KzCh51VGD9wGNOO8lhwzgTeZ4XoNxN+6Cwh3GHZ7zRbDX64Pvj51d0aGWDcsWsRnhqfJZ2CKYXI7RAErlIg3G5BZEplACm4ZBKAyJSCcLsFgasURG6HvCfxGhqfJfWahNFWEaY8Sur7i4hvrgCjDghv2xB53YrI61ZMvzgtOwm2VcjBg20VMXVenJbXC2/bgFEHxDdXoj45EwhTDsJoqxKCD9pq548N3tsb8bVO8T5rVHrOBJH9haQ8wYz5Lh+C50JV2nmRKY364Ezgh84S3mdFxNc6NTZ4b29CPzDJXq2O+O2ej0N924hbf2GuCg720Wg3H8LvJ3/D8RM1aG74FZMPyzPuAUODuPUXPg71bYv47Z5J9mq1DOB0ti10OtsWUhQVbdPduoMJjSVTCsufx2G5eAiWi4dwsqYO//x9HO8cFRjrKMO/l47gZE2dPN/wx4lZLyFjCG7dQakNj4+XcgCUIvjYkAevoVdKwWhHBfpvmdB/y4R3jgrMTs07R+K8BA6voTf42JD3Nd8VCbUhcHRp9J9y7l4h4cQefafA0aVJvd+3DJvNNi/s1K4kbMkRuPWt0SsbD2QM4anxGdz6VsKWHAk7tSvlr57vPQBKMfawdsFU7+6l8Tb2sHbBt8j8H5wn/RXZElZDAAAAAElFTkSuQmCC"/>
            </Head>
            <Header/>
            <Main/>
            <footer className={styles.footer}>

            </footer>
        </>
    )
}
