import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Header from "../components/Header";
import Main from "../components/Main";

export default function Home() {
    return (
        <>
            <Head>
                <title>#budget10</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Header/>
            <Main/>
            <footer className={styles.footer}>

            </footer>
        </>
    )
}
